services:
  redis:
    image: redis:7-alpine
    container_name: matchingo-redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no # Disable persistence for testing
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: matchingo-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: echo stat | nc localhost 2181 || exit 1
      interval: 1s
      timeout: 3s
      retries: 30

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: matchingo-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: matchingo-server
    ports:
      - "50051:50051"  # gRPC port
      - "8080:8080"    # HTTP port
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - LOG_LEVEL=debug
      - LOG_FORMAT=pretty
    command: ["matchingo-server", "-grpc_port=50051", "-http_port=8080", "-log_level=debug", "-log_format=pretty"]

  marketmaker:
    build:
      context: .
      dockerfile: Dockerfile.marketmaker
    container_name: matchingo-marketmaker
    depends_on:
      server:
        condition: service_started
    environment:
      - MATCHINGO_GRPC_ADDR=server:50051
      - MARKET_SYMBOL=BTC-USDT
      - EXTERNAL_SYMBOL=BTCUSDT
      - PRICE_SOURCE_URL=https://api.binance.com
      - NUM_LEVELS=3
      - BASE_SPREAD_PERCENT=0.1
      - PRICE_STEP_PERCENT=0.05
      - ORDER_SIZE=0.01
      - UPDATE_INTERVAL_SECONDS=10
      - MARKET_MAKER_ID=mm-01
      - HTTP_TIMEOUT_SECONDS=5
      - MAX_RETRIES=3
      - LOG_LEVEL=debug 