// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/api/proto/orderbook.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of backend storage for the order book
type BackendType int32

const (
	BackendType_MEMORY BackendType = 0
	BackendType_REDIS  BackendType = 1
)

// Enum value maps for BackendType.
var (
	BackendType_name = map[int32]string{
		0: "MEMORY",
		1: "REDIS",
	}
	BackendType_value = map[string]int32{
		"MEMORY": 0,
		"REDIS":  1,
	}
)

func (x BackendType) Enum() *BackendType {
	p := new(BackendType)
	*p = x
	return p
}

func (x BackendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackendType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_proto_orderbook_proto_enumTypes[0].Descriptor()
}

func (BackendType) Type() protoreflect.EnumType {
	return &file_pkg_api_proto_orderbook_proto_enumTypes[0]
}

func (x BackendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackendType.Descriptor instead.
func (BackendType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{0}
}

// Types of orders
type OrderType int32

const (
	OrderType_LIMIT      OrderType = 0
	OrderType_MARKET     OrderType = 1
	OrderType_STOP       OrderType = 2
	OrderType_STOP_LIMIT OrderType = 3
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "LIMIT",
		1: "MARKET",
		2: "STOP",
		3: "STOP_LIMIT",
	}
	OrderType_value = map[string]int32{
		"LIMIT":      0,
		"MARKET":     1,
		"STOP":       2,
		"STOP_LIMIT": 3,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_proto_orderbook_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_pkg_api_proto_orderbook_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{1}
}

// Order side: buy or sell
type OrderSide int32

const (
	OrderSide_BUY  OrderSide = 0
	OrderSide_SELL OrderSide = 1
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	OrderSide_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_proto_orderbook_proto_enumTypes[2].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_pkg_api_proto_orderbook_proto_enumTypes[2]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{2}
}

// Time in force for orders
type TimeInForce int32

const (
	TimeInForce_GTC TimeInForce = 0 // Good Till Canceled
	TimeInForce_IOC TimeInForce = 1 // Immediate or Cancel
	TimeInForce_FOK TimeInForce = 2 // Fill or Kill
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "GTC",
		1: "IOC",
		2: "FOK",
	}
	TimeInForce_value = map[string]int32{
		"GTC": 0,
		"IOC": 1,
		"FOK": 2,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_proto_orderbook_proto_enumTypes[3].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_pkg_api_proto_orderbook_proto_enumTypes[3]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{3}
}

// Status of an order
type OrderStatus int32

const (
	OrderStatus_PENDING          OrderStatus = 0
	OrderStatus_OPEN             OrderStatus = 1
	OrderStatus_FILLED           OrderStatus = 2
	OrderStatus_PARTIALLY_FILLED OrderStatus = 3
	OrderStatus_CANCELED         OrderStatus = 4
	OrderStatus_REJECTED         OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "OPEN",
		2: "FILLED",
		3: "PARTIALLY_FILLED",
		4: "CANCELED",
		5: "REJECTED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":          0,
		"OPEN":             1,
		"FILLED":           2,
		"PARTIALLY_FILLED": 3,
		"CANCELED":         4,
		"REJECTED":         5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_proto_orderbook_proto_enumTypes[4].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_proto_orderbook_proto_enumTypes[4]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{4}
}

// Request to create a new order book
type CreateOrderBookRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BackendType BackendType            `protobuf:"varint,2,opt,name=backend_type,json=backendType,proto3,enum=matchingo.api.BackendType" json:"backend_type,omitempty"`
	// Backend-specific options, such as Redis connection details
	Options       map[string]string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderBookRequest) Reset() {
	*x = CreateOrderBookRequest{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderBookRequest) ProtoMessage() {}

func (x *CreateOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderBookRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderBookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrderBookRequest) GetBackendType() BackendType {
	if x != nil {
		return x.BackendType
	}
	return BackendType_MEMORY
}

func (x *CreateOrderBookRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// Response containing order book information
type OrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BackendType   BackendType            `protobuf:"varint,2,opt,name=backend_type,json=backendType,proto3,enum=matchingo.api.BackendType" json:"backend_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OrderCount    uint64                 `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookResponse) Reset() {
	*x = OrderBookResponse{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookResponse) ProtoMessage() {}

func (x *OrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookResponse.ProtoReflect.Descriptor instead.
func (*OrderBookResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *OrderBookResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderBookResponse) GetBackendType() BackendType {
	if x != nil {
		return x.BackendType
	}
	return BackendType_MEMORY
}

func (x *OrderBookResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderBookResponse) GetOrderCount() uint64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

// Request to retrieve an order book
type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderBookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to list all order books
type ListOrderBooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For pagination, the maximum number of items to return
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// For pagination, the offset from which to start returning items
	Offset        int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderBooksRequest) Reset() {
	*x = ListOrderBooksRequest{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderBooksRequest) ProtoMessage() {}

func (x *ListOrderBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderBooksRequest.ProtoReflect.Descriptor instead.
func (*ListOrderBooksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrderBooksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrderBooksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response containing a list of order books
type ListOrderBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderBooks    []*OrderBookResponse   `protobuf:"bytes,1,rep,name=order_books,json=orderBooks,proto3" json:"order_books,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderBooksResponse) Reset() {
	*x = ListOrderBooksResponse{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderBooksResponse) ProtoMessage() {}

func (x *ListOrderBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderBooksResponse.ProtoReflect.Descriptor instead.
func (*ListOrderBooksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrderBooksResponse) GetOrderBooks() []*OrderBookResponse {
	if x != nil {
		return x.OrderBooks
	}
	return nil
}

func (x *ListOrderBooksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Request to delete an order book
type DeleteOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderBookRequest) Reset() {
	*x = DeleteOrderBookRequest{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderBookRequest) ProtoMessage() {}

func (x *DeleteOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteOrderBookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to create a new order
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderBookName string                 `protobuf:"bytes,1,opt,name=order_book_name,json=orderBookName,proto3" json:"order_book_name,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Side          OrderSide              `protobuf:"varint,3,opt,name=side,proto3,enum=matchingo.api.OrderSide" json:"side,omitempty"`
	Quantity      string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         string                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	OrderType     OrderType              `protobuf:"varint,6,opt,name=order_type,json=orderType,proto3,enum=matchingo.api.OrderType" json:"order_type,omitempty"`
	TimeInForce   TimeInForce            `protobuf:"varint,7,opt,name=time_in_force,json=timeInForce,proto3,enum=matchingo.api.TimeInForce" json:"time_in_force,omitempty"`
	StopPrice     string                 `protobuf:"bytes,8,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`        // Only for stop orders
	OcoId         string                 `protobuf:"bytes,9,opt,name=oco_id,json=ocoId,proto3" json:"oco_id,omitempty"`                    // Only for OCO orders
	UserAddress   string                 `protobuf:"bytes,10,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"` // User's wallet address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderRequest) GetOrderBookName() string {
	if x != nil {
		return x.OrderBookName
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

func (x *CreateOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *CreateOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_LIMIT
}

func (x *CreateOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_GTC
}

func (x *CreateOrderRequest) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *CreateOrderRequest) GetOcoId() string {
	if x != nil {
		return x.OcoId
	}
	return ""
}

func (x *CreateOrderRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

// Response containing order information
type OrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderBookName     string                 `protobuf:"bytes,2,opt,name=order_book_name,json=orderBookName,proto3" json:"order_book_name,omitempty"`
	Side              OrderSide              `protobuf:"varint,3,opt,name=side,proto3,enum=matchingo.api.OrderSide" json:"side,omitempty"`
	Quantity          string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price             string                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	OrderType         OrderType              `protobuf:"varint,6,opt,name=order_type,json=orderType,proto3,enum=matchingo.api.OrderType" json:"order_type,omitempty"`
	TimeInForce       TimeInForce            `protobuf:"varint,7,opt,name=time_in_force,json=timeInForce,proto3,enum=matchingo.api.TimeInForce" json:"time_in_force,omitempty"`
	StopPrice         string                 `protobuf:"bytes,8,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	Status            OrderStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=matchingo.api.OrderStatus" json:"status,omitempty"`
	FilledQuantity    string                 `protobuf:"bytes,10,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	RemainingQuantity string                 `protobuf:"bytes,11,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Fills             []*Fill                `protobuf:"bytes,14,rep,name=fills,proto3" json:"fills,omitempty"`
	OcoId             string                 `protobuf:"bytes,15,opt,name=oco_id,json=ocoId,proto3" json:"oco_id,omitempty"`
	UserAddress       string                 `protobuf:"bytes,16,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"` // User's wallet address
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{7}
}

func (x *OrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderResponse) GetOrderBookName() string {
	if x != nil {
		return x.OrderBookName
	}
	return ""
}

func (x *OrderResponse) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

func (x *OrderResponse) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *OrderResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderResponse) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_LIMIT
}

func (x *OrderResponse) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_GTC
}

func (x *OrderResponse) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *OrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *OrderResponse) GetFilledQuantity() string {
	if x != nil {
		return x.FilledQuantity
	}
	return ""
}

func (x *OrderResponse) GetRemainingQuantity() string {
	if x != nil {
		return x.RemainingQuantity
	}
	return ""
}

func (x *OrderResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *OrderResponse) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

func (x *OrderResponse) GetOcoId() string {
	if x != nil {
		return x.OcoId
	}
	return ""
}

func (x *OrderResponse) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

// Represents a fill (trade) that has occurred
type Fill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fill) Reset() {
	*x = Fill{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fill) ProtoMessage() {}

func (x *Fill) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fill.ProtoReflect.Descriptor instead.
func (*Fill) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{8}
}

func (x *Fill) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Fill) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Fill) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Request to retrieve an order
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderBookName string                 `protobuf:"bytes,1,opt,name=order_book_name,json=orderBookName,proto3" json:"order_book_name,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderRequest) GetOrderBookName() string {
	if x != nil {
		return x.OrderBookName
	}
	return ""
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Request to cancel an order
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderBookName string                 `protobuf:"bytes,1,opt,name=order_book_name,json=orderBookName,proto3" json:"order_book_name,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOrderRequest) GetOrderBookName() string {
	if x != nil {
		return x.OrderBookName
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Request to get the current state of an order book
type GetOrderBookStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional number of price levels to retrieve
	Depth         int32 `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookStateRequest) Reset() {
	*x = GetOrderBookStateRequest{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookStateRequest) ProtoMessage() {}

func (x *GetOrderBookStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookStateRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookStateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderBookStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetOrderBookStateRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// Response containing order book state
type OrderBookStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookStateResponse) Reset() {
	*x = OrderBookStateResponse{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookStateResponse) ProtoMessage() {}

func (x *OrderBookStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookStateResponse.ProtoReflect.Descriptor instead.
func (*OrderBookStateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{12}
}

func (x *OrderBookStateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderBookStateResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBookStateResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OrderBookStateResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Represents a price level in the order book
type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	TotalQuantity string                 `protobuf:"bytes,2,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	OrderCount    int32                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	UserAddress   string                 `protobuf:"bytes,4,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"` // User's wallet address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{13}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetTotalQuantity() string {
	if x != nil {
		return x.TotalQuantity
	}
	return ""
}

func (x *PriceLevel) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *PriceLevel) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

// Represents a trade that has occurred
type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsQuote       bool                   `protobuf:"varint,5,opt,name=is_quote,json=isQuote,proto3" json:"is_quote,omitempty"`
	UserAddress   string                 `protobuf:"bytes,6,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"` // User's wallet address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{14}
}

func (x *Trade) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Trade) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Trade) GetIsQuote() bool {
	if x != nil {
		return x.IsQuote
	}
	return false
}

func (x *Trade) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

// DoneMessage represents the message structure for the Done object
// to be sent to the message queue
type DoneMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ExecutedQuantity  string                 `protobuf:"bytes,2,opt,name=executed_quantity,json=executedQuantity,proto3" json:"executed_quantity,omitempty"`
	RemainingQuantity string                 `protobuf:"bytes,3,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"`
	Trades            []*Trade               `protobuf:"bytes,4,rep,name=trades,proto3" json:"trades,omitempty"`
	Canceled          []string               `protobuf:"bytes,5,rep,name=canceled,proto3" json:"canceled,omitempty"`
	Activated         []string               `protobuf:"bytes,6,rep,name=activated,proto3" json:"activated,omitempty"`
	Stored            bool                   `protobuf:"varint,7,opt,name=stored,proto3" json:"stored,omitempty"`
	Quantity          string                 `protobuf:"bytes,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Processed         string                 `protobuf:"bytes,9,opt,name=processed,proto3" json:"processed,omitempty"`
	Left              string                 `protobuf:"bytes,10,opt,name=left,proto3" json:"left,omitempty"`
	UserAddress       string                 `protobuf:"bytes,11,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"` // User's wallet address
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DoneMessage) Reset() {
	*x = DoneMessage{}
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneMessage) ProtoMessage() {}

func (x *DoneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_orderbook_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneMessage.ProtoReflect.Descriptor instead.
func (*DoneMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_orderbook_proto_rawDescGZIP(), []int{15}
}

func (x *DoneMessage) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DoneMessage) GetExecutedQuantity() string {
	if x != nil {
		return x.ExecutedQuantity
	}
	return ""
}

func (x *DoneMessage) GetRemainingQuantity() string {
	if x != nil {
		return x.RemainingQuantity
	}
	return ""
}

func (x *DoneMessage) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *DoneMessage) GetCanceled() []string {
	if x != nil {
		return x.Canceled
	}
	return nil
}

func (x *DoneMessage) GetActivated() []string {
	if x != nil {
		return x.Activated
	}
	return nil
}

func (x *DoneMessage) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *DoneMessage) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *DoneMessage) GetProcessed() string {
	if x != nil {
		return x.Processed
	}
	return ""
}

func (x *DoneMessage) GetLeft() string {
	if x != nil {
		return x.Left
	}
	return ""
}

func (x *DoneMessage) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

var File_pkg_api_proto_orderbook_proto protoreflect.FileDescriptor

const file_pkg_api_proto_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/api/proto/orderbook.proto\x12\rmatchingo.api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf5\x01\n" +
	"\x16CreateOrderBookRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\fbackend_type\x18\x02 \x01(\x0e2\x1a.matchingo.api.BackendTypeR\vbackendType\x12L\n" +
	"\aoptions\x18\x03 \x03(\v22.matchingo.api.CreateOrderBookRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x01\n" +
	"\x11OrderBookResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\fbackend_type\x18\x02 \x01(\x0e2\x1a.matchingo.api.BackendTypeR\vbackendType\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vorder_count\x18\x04 \x01(\x04R\n" +
	"orderCount\")\n" +
	"\x13GetOrderBookRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"E\n" +
	"\x15ListOrderBooksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"q\n" +
	"\x16ListOrderBooksResponse\x12A\n" +
	"\vorder_books\x18\x01 \x03(\v2 .matchingo.api.OrderBookResponseR\n" +
	"orderBooks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\",\n" +
	"\x16DeleteOrderBookRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x89\x03\n" +
	"\x12CreateOrderRequest\x12&\n" +
	"\x0forder_book_name\x18\x01 \x01(\tR\rorderBookName\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12,\n" +
	"\x04side\x18\x03 \x01(\x0e2\x18.matchingo.api.OrderSideR\x04side\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x127\n" +
	"\n" +
	"order_type\x18\x06 \x01(\x0e2\x18.matchingo.api.OrderTypeR\torderType\x12>\n" +
	"\rtime_in_force\x18\a \x01(\x0e2\x1a.matchingo.api.TimeInForceR\vtimeInForce\x12\x1d\n" +
	"\n" +
	"stop_price\x18\b \x01(\tR\tstopPrice\x12\x15\n" +
	"\x06oco_id\x18\t \x01(\tR\x05ocoId\x12!\n" +
	"\fuser_address\x18\n" +
	" \x01(\tR\vuserAddress\"\xb1\x05\n" +
	"\rOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12&\n" +
	"\x0forder_book_name\x18\x02 \x01(\tR\rorderBookName\x12,\n" +
	"\x04side\x18\x03 \x01(\x0e2\x18.matchingo.api.OrderSideR\x04side\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x127\n" +
	"\n" +
	"order_type\x18\x06 \x01(\x0e2\x18.matchingo.api.OrderTypeR\torderType\x12>\n" +
	"\rtime_in_force\x18\a \x01(\x0e2\x1a.matchingo.api.TimeInForceR\vtimeInForce\x12\x1d\n" +
	"\n" +
	"stop_price\x18\b \x01(\tR\tstopPrice\x122\n" +
	"\x06status\x18\t \x01(\x0e2\x1a.matchingo.api.OrderStatusR\x06status\x12'\n" +
	"\x0ffilled_quantity\x18\n" +
	" \x01(\tR\x0efilledQuantity\x12-\n" +
	"\x12remaining_quantity\x18\v \x01(\tR\x11remainingQuantity\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\x05fills\x18\x0e \x03(\v2\x13.matchingo.api.FillR\x05fills\x12\x15\n" +
	"\x06oco_id\x18\x0f \x01(\tR\x05ocoId\x12!\n" +
	"\fuser_address\x18\x10 \x01(\tR\vuserAddress\"r\n" +
	"\x04Fill\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"T\n" +
	"\x0fGetOrderRequest\x12&\n" +
	"\x0forder_book_name\x18\x01 \x01(\tR\rorderBookName\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"W\n" +
	"\x12CancelOrderRequest\x12&\n" +
	"\x0forder_book_name\x18\x01 \x01(\tR\rorderBookName\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"D\n" +
	"\x18GetOrderBookStateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"\xc4\x01\n" +
	"\x16OrderBookStateResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x04bids\x18\x02 \x03(\v2\x19.matchingo.api.PriceLevelR\x04bids\x12-\n" +
	"\x04asks\x18\x03 \x03(\v2\x19.matchingo.api.PriceLevelR\x04asks\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x8d\x01\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12%\n" +
	"\x0etotal_quantity\x18\x02 \x01(\tR\rtotalQuantity\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x05R\n" +
	"orderCount\x12!\n" +
	"\fuser_address\x18\x04 \x01(\tR\vuserAddress\"\xa6\x01\n" +
	"\x05Trade\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12\x19\n" +
	"\bis_quote\x18\x05 \x01(\bR\aisQuote\x12!\n" +
	"\fuser_address\x18\x06 \x01(\tR\vuserAddress\"\xf5\x02\n" +
	"\vDoneMessage\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12+\n" +
	"\x11executed_quantity\x18\x02 \x01(\tR\x10executedQuantity\x12-\n" +
	"\x12remaining_quantity\x18\x03 \x01(\tR\x11remainingQuantity\x12,\n" +
	"\x06trades\x18\x04 \x03(\v2\x14.matchingo.api.TradeR\x06trades\x12\x1a\n" +
	"\bcanceled\x18\x05 \x03(\tR\bcanceled\x12\x1c\n" +
	"\tactivated\x18\x06 \x03(\tR\tactivated\x12\x16\n" +
	"\x06stored\x18\a \x01(\bR\x06stored\x12\x1a\n" +
	"\bquantity\x18\b \x01(\tR\bquantity\x12\x1c\n" +
	"\tprocessed\x18\t \x01(\tR\tprocessed\x12\x12\n" +
	"\x04left\x18\n" +
	" \x01(\tR\x04left\x12!\n" +
	"\fuser_address\x18\v \x01(\tR\vuserAddress*$\n" +
	"\vBackendType\x12\n" +
	"\n" +
	"\x06MEMORY\x10\x00\x12\t\n" +
	"\x05REDIS\x10\x01*<\n" +
	"\tOrderType\x12\t\n" +
	"\x05LIMIT\x10\x00\x12\n" +
	"\n" +
	"\x06MARKET\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\x0e\n" +
	"\n" +
	"STOP_LIMIT\x10\x03*\x1e\n" +
	"\tOrderSide\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x01*(\n" +
	"\vTimeInForce\x12\a\n" +
	"\x03GTC\x10\x00\x12\a\n" +
	"\x03IOC\x10\x01\x12\a\n" +
	"\x03FOK\x10\x02*b\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\n" +
	"\n" +
	"\x06FILLED\x10\x02\x12\x14\n" +
	"\x10PARTIALLY_FILLED\x10\x03\x12\f\n" +
	"\bCANCELED\x10\x04\x12\f\n" +
	"\bREJECTED\x10\x052\xbe\x05\n" +
	"\x10OrderBookService\x12Z\n" +
	"\x0fCreateOrderBook\x12%.matchingo.api.CreateOrderBookRequest\x1a .matchingo.api.OrderBookResponse\x12T\n" +
	"\fGetOrderBook\x12\".matchingo.api.GetOrderBookRequest\x1a .matchingo.api.OrderBookResponse\x12]\n" +
	"\x0eListOrderBooks\x12$.matchingo.api.ListOrderBooksRequest\x1a%.matchingo.api.ListOrderBooksResponse\x12P\n" +
	"\x0fDeleteOrderBook\x12%.matchingo.api.DeleteOrderBookRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\vCreateOrder\x12!.matchingo.api.CreateOrderRequest\x1a\x1c.matchingo.api.OrderResponse\x12H\n" +
	"\bGetOrder\x12\x1e.matchingo.api.GetOrderRequest\x1a\x1c.matchingo.api.OrderResponse\x12H\n" +
	"\vCancelOrder\x12!.matchingo.api.CancelOrderRequest\x1a\x16.google.protobuf.Empty\x12c\n" +
	"\x11GetOrderBookState\x12'.matchingo.api.GetOrderBookStateRequest\x1a%.matchingo.api.OrderBookStateResponseB+Z)github.com/erain9/matchingo/pkg/api/protob\x06proto3"

var (
	file_pkg_api_proto_orderbook_proto_rawDescOnce sync.Once
	file_pkg_api_proto_orderbook_proto_rawDescData []byte
)

func file_pkg_api_proto_orderbook_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_orderbook_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_orderbook_proto_rawDesc), len(file_pkg_api_proto_orderbook_proto_rawDesc)))
	})
	return file_pkg_api_proto_orderbook_proto_rawDescData
}

var file_pkg_api_proto_orderbook_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pkg_api_proto_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_api_proto_orderbook_proto_goTypes = []any{
	(BackendType)(0),                 // 0: matchingo.api.BackendType
	(OrderType)(0),                   // 1: matchingo.api.OrderType
	(OrderSide)(0),                   // 2: matchingo.api.OrderSide
	(TimeInForce)(0),                 // 3: matchingo.api.TimeInForce
	(OrderStatus)(0),                 // 4: matchingo.api.OrderStatus
	(*CreateOrderBookRequest)(nil),   // 5: matchingo.api.CreateOrderBookRequest
	(*OrderBookResponse)(nil),        // 6: matchingo.api.OrderBookResponse
	(*GetOrderBookRequest)(nil),      // 7: matchingo.api.GetOrderBookRequest
	(*ListOrderBooksRequest)(nil),    // 8: matchingo.api.ListOrderBooksRequest
	(*ListOrderBooksResponse)(nil),   // 9: matchingo.api.ListOrderBooksResponse
	(*DeleteOrderBookRequest)(nil),   // 10: matchingo.api.DeleteOrderBookRequest
	(*CreateOrderRequest)(nil),       // 11: matchingo.api.CreateOrderRequest
	(*OrderResponse)(nil),            // 12: matchingo.api.OrderResponse
	(*Fill)(nil),                     // 13: matchingo.api.Fill
	(*GetOrderRequest)(nil),          // 14: matchingo.api.GetOrderRequest
	(*CancelOrderRequest)(nil),       // 15: matchingo.api.CancelOrderRequest
	(*GetOrderBookStateRequest)(nil), // 16: matchingo.api.GetOrderBookStateRequest
	(*OrderBookStateResponse)(nil),   // 17: matchingo.api.OrderBookStateResponse
	(*PriceLevel)(nil),               // 18: matchingo.api.PriceLevel
	(*Trade)(nil),                    // 19: matchingo.api.Trade
	(*DoneMessage)(nil),              // 20: matchingo.api.DoneMessage
	nil,                              // 21: matchingo.api.CreateOrderBookRequest.OptionsEntry
	(*timestamppb.Timestamp)(nil),    // 22: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 23: google.protobuf.Empty
}
var file_pkg_api_proto_orderbook_proto_depIdxs = []int32{
	0,  // 0: matchingo.api.CreateOrderBookRequest.backend_type:type_name -> matchingo.api.BackendType
	21, // 1: matchingo.api.CreateOrderBookRequest.options:type_name -> matchingo.api.CreateOrderBookRequest.OptionsEntry
	0,  // 2: matchingo.api.OrderBookResponse.backend_type:type_name -> matchingo.api.BackendType
	22, // 3: matchingo.api.OrderBookResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 4: matchingo.api.ListOrderBooksResponse.order_books:type_name -> matchingo.api.OrderBookResponse
	2,  // 5: matchingo.api.CreateOrderRequest.side:type_name -> matchingo.api.OrderSide
	1,  // 6: matchingo.api.CreateOrderRequest.order_type:type_name -> matchingo.api.OrderType
	3,  // 7: matchingo.api.CreateOrderRequest.time_in_force:type_name -> matchingo.api.TimeInForce
	2,  // 8: matchingo.api.OrderResponse.side:type_name -> matchingo.api.OrderSide
	1,  // 9: matchingo.api.OrderResponse.order_type:type_name -> matchingo.api.OrderType
	3,  // 10: matchingo.api.OrderResponse.time_in_force:type_name -> matchingo.api.TimeInForce
	4,  // 11: matchingo.api.OrderResponse.status:type_name -> matchingo.api.OrderStatus
	22, // 12: matchingo.api.OrderResponse.created_at:type_name -> google.protobuf.Timestamp
	22, // 13: matchingo.api.OrderResponse.updated_at:type_name -> google.protobuf.Timestamp
	13, // 14: matchingo.api.OrderResponse.fills:type_name -> matchingo.api.Fill
	22, // 15: matchingo.api.Fill.timestamp:type_name -> google.protobuf.Timestamp
	18, // 16: matchingo.api.OrderBookStateResponse.bids:type_name -> matchingo.api.PriceLevel
	18, // 17: matchingo.api.OrderBookStateResponse.asks:type_name -> matchingo.api.PriceLevel
	22, // 18: matchingo.api.OrderBookStateResponse.timestamp:type_name -> google.protobuf.Timestamp
	19, // 19: matchingo.api.DoneMessage.trades:type_name -> matchingo.api.Trade
	5,  // 20: matchingo.api.OrderBookService.CreateOrderBook:input_type -> matchingo.api.CreateOrderBookRequest
	7,  // 21: matchingo.api.OrderBookService.GetOrderBook:input_type -> matchingo.api.GetOrderBookRequest
	8,  // 22: matchingo.api.OrderBookService.ListOrderBooks:input_type -> matchingo.api.ListOrderBooksRequest
	10, // 23: matchingo.api.OrderBookService.DeleteOrderBook:input_type -> matchingo.api.DeleteOrderBookRequest
	11, // 24: matchingo.api.OrderBookService.CreateOrder:input_type -> matchingo.api.CreateOrderRequest
	14, // 25: matchingo.api.OrderBookService.GetOrder:input_type -> matchingo.api.GetOrderRequest
	15, // 26: matchingo.api.OrderBookService.CancelOrder:input_type -> matchingo.api.CancelOrderRequest
	16, // 27: matchingo.api.OrderBookService.GetOrderBookState:input_type -> matchingo.api.GetOrderBookStateRequest
	6,  // 28: matchingo.api.OrderBookService.CreateOrderBook:output_type -> matchingo.api.OrderBookResponse
	6,  // 29: matchingo.api.OrderBookService.GetOrderBook:output_type -> matchingo.api.OrderBookResponse
	9,  // 30: matchingo.api.OrderBookService.ListOrderBooks:output_type -> matchingo.api.ListOrderBooksResponse
	23, // 31: matchingo.api.OrderBookService.DeleteOrderBook:output_type -> google.protobuf.Empty
	12, // 32: matchingo.api.OrderBookService.CreateOrder:output_type -> matchingo.api.OrderResponse
	12, // 33: matchingo.api.OrderBookService.GetOrder:output_type -> matchingo.api.OrderResponse
	23, // 34: matchingo.api.OrderBookService.CancelOrder:output_type -> google.protobuf.Empty
	17, // 35: matchingo.api.OrderBookService.GetOrderBookState:output_type -> matchingo.api.OrderBookStateResponse
	28, // [28:36] is the sub-list for method output_type
	20, // [20:28] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_orderbook_proto_init() }
func file_pkg_api_proto_orderbook_proto_init() {
	if File_pkg_api_proto_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_orderbook_proto_rawDesc), len(file_pkg_api_proto_orderbook_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_orderbook_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_orderbook_proto_depIdxs,
		EnumInfos:         file_pkg_api_proto_orderbook_proto_enumTypes,
		MessageInfos:      file_pkg_api_proto_orderbook_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_orderbook_proto = out.File
	file_pkg_api_proto_orderbook_proto_goTypes = nil
	file_pkg_api_proto_orderbook_proto_depIdxs = nil
}
