# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Install Protoc
      run: |
        sudo apt-get update && sudo apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        
    - name: Install goimports
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        
    # Option 1: Step-by-step approach (currently used)
    - name: Generate Protobuf
      run: make proto
        
    - name: Build
      run: make build
        
    # Option 2: All-in-one approach (alternative)
    # - name: Build All
    #   run: make build-all
        
    - name: Test
      run: make test
