# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: "yes"
        options: >-
          --health-cmd="echo ruok | nc localhost 2181 | grep imok"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_LISTENERS: PLAINTEXT://:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CFG_KAFKA_ENABLE_KRAFT: "no"
        options: >-
          --health-cmd="kafka-topics.sh --bootstrap-server localhost:9092 --list"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    # Wait for Kafka to be healthy (optional, but recommended for reliability)
    - name: Wait for Kafka
      run: |
        for i in {1..10}; do
          nc -z localhost 9092 && echo "Kafka is up" && exit 0
          echo "Waiting for Kafka..."
          sleep 5
        done
        echo "Kafka did not start in time" && exit 1

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true
        
    - name: Install Protoc and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install golang.org/x/tools/cmd/goimports@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        
    - name: Generate Protobuf
      run: make proto

    - name: Update dependencies
      run: go mod tidy
        
    - name: Build
      run: make build
        
    - name: Test
      env:
        REDIS_ADDR: localhost:6379
      run: |
        # Run unit tests
        go test -v ./pkg/... -count=1

        # Run only working integration tests
        go test -v ./test/integration/... -run "TestIntegrationV2_(BasicLimitOrder|LimitOrderMatch|MarketOrderMatch|CancelOrder|IOC_FOK)" -count=1
